# Generated by Django 4.2.5 on 2023-09-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_alter_device_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='checked_out_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.employee'),
        ),
    ]
