# Generated by Django 4.2.5 on 2023-09-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0005_device_checked_in_device_checked_in_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceLog',
        ),
    ]
