# Generated by Django 4.2.5 on 2023-09-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0006_delete_devicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
